name: deploy
on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build and Publish
        uses: VaultVulp/gp-docker-action@1.6.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          image-name: databack-pro
          custom-args: --build-arg=GIT_TOKEN=${{ secrets.GIT_TOKEN }}
  deploy:
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: Deploy
        uses: steebchen/kubectl@v2.0.0
        with:
          config: ${{ secrets.KUBE_CONFIG }}
          command: rollout restart deployment databack-pro databack-pro-demo
